version: "3.9"

services:
  app:
    container_name: godevrelbackend
    build:
      context: .
      target: development
    ports:
      - 4000:4000
    command: npm run start:dev
    volumes:
      - ./:/app
      - /app/node_modules
    env_file: ./.env
    depends_on:
      - postgres
      - mongodb
      - redis
    networks:
      - devrel

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - devrel

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./temp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - devrel

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASS}
    depends_on:
      - postgres
    networks:
      - devrel

networks:
  devrel:
