version: "3.9"

services:
  redis-compose:
    image: redis:latest
    ports:
      - 6379:6379

  backend-db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./temp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: devrel
      POSTGRES_PASSWORD: devrel
