version: "3.9"

services:
  redis-compose:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - devrel

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./temp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - devrel

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASS}
    networks:
      - devrel

networks:
  devrel:
