// ERRORS
export const ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND";
export const ERROR_INVALID_CREDENTIALS = "ERROR_INVALID_CREDENTIALS";
export const ERROR_INVALID_TOKEN = "ERROR_INVALID_TOKEN";
export const ERROR_EMAIL_NOT_FOUND = "ERROR_EMAIL_NOT_FOUND";
export const ERROR_ID_IS_REQUIRED = "ERROR_ID_IS_REQUIRED";

export const FORM_NOT_FOUND = "FORM_NOT_FOUND";
export const FORM_INVALID_ID = "FORM_INVALID_ID";



//SUCCESS
export const SUCCESSFULLY_DELETED = "SUCCESSFULLY_DELETED";
export const SUCCESSFULLY_VALIDATED = "SUCCESSFULLY_VALIDATED";


//DATABASE NAME
export const MONGODB_CONNECTION = "MONGODB_CONNECTION";
export const POSTGRES_CONNECTION = "POSTGRES_CONNECTION";
